services:
  cli_tool:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: mparty
    container_name: mparty
    volumes:
      - ./m_party.py:/opt/conda/bin/m_party.py
      - ./workflow/:/opt/conda/bin/workflow
    stdin_open: true
    tty: true