services:
  cli_tool:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: mparty
    container_name: mparty
    volumes:
      - ./m_party.py:/app/m_party.py
      - ./workflow/:/app/workflow
      - ./resources/:/app/resources
    stdin_open: true
    tty: true
